version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: chore"
      - "scope: docker"
      - "dependencies: docker"
      - "bot: dependabot"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: chore"
      - "scope: docker"
      - "dependencies: docker"
      - "bot: dependabot"
