services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=automation
    labels:
      - "ofelia.enabled=true"
      - "ofelia.job-exec.scheduled-job.schedule=@hourly"
      - "ofelia.job-exec.scheduled-job.command=/bin/bash hourly_run.sh"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./:/app
      - ~/.gitconfig:/home/msilva/.gitconfig:ro
      - ~/.ssh:/home/msilva/.ssh:ro
    networks:
      - consul_consul

  ofelia:
    image: mcuadros/ofelia:v0.3.9
    container_name: ofelia
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  consul_consul:
    external: true
